config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "welcome#index"

  resources :games
  resources :locations

  resources :users, only: [:index, :show]

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :location
  belongs_to :user

  def points
    if elapsed_time == 0
      score * 1
    else
      score * elapsed_time
    end
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :games, dependent: :destroy
  has_many :users, through: :games

  def self.random
    order("RANDOM()").first
  end

  def top_scorer
    users.order("score ASC").first
  end

  def top_game
    games.order("score ASC").first
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :games, dependent: :destroy
  has_many :locations, through: :games

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_params, if: :devise_controller?

  private
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :username]
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name, :username]
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!

  def index
    @games = current_user.games
    @locations = current_user.locations
  end

  def new
    @game = Game.new
    location_ids = current_user.games.pluck(:location_id)
    @location = Location.where.not(id: location_ids).random
    if @location == nil
      redirect_to users_path, notice: "Congrats you have played all the levels! Stay tuned for more..."
    end
  end

  def create
    @location = Location.find(params[:game][:location_id])
    @game = current_user.games.new(game_params)
    @game.location = @location
    @game.score = Geocoder::Calculations.distance_between([@location.latitude, @location.longitude], [@game.lat_guess, @game.lng_guess]).round(2)
      if @game.save
        redirect_to @game
      else
        render :new
      end
  end

  def show
    @game = Game.find(params[:id])
    @games = Game.all
    @location = Location.find(@game.location.id)
  end

  private
  def game_params
    params.require(:game).permit(:lat_guess, :lng_guess, :score, :elapsed_time)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def create
    @location = Location.find(params[:id]).random
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
  
  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "external"
  
  def index
    # @game = Game.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/index.html.erb
<table class="ui sortable celled table">
  <thead>
    <tr>
      <th><i style="color:#CCC2C2;" class="fa fa-diamond fa-2x"></i>    Platinum</th>
      <th><i style="color:#D9A441;" class="fa fa-diamond fa-2x"></i>    Gold</th>
      <th><i style="color:#A8A8A8;" class="fa fa-diamond fa-2x"></i>    Silver</th>
      <th><i style="color:#965A38;" class="fa fa-diamond fa-2x"></i>    Bronze</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Score: 0-100</td>
      <td>Score: 101-2000</td>
      <td>Score: 2001-5000</td>
      <td>Score: 5000+</td>
    </tr>
  </tbody>
</table>
<p id="score">Score = Distance Away x Time Taken</p>

<h1 style="text-align: center">Your Scores</h1>
<table class="ui sortable celled table">
  <thead>
    <tr>
      <th>Level</th>
      <th>Distance Away</th>
      <th>Time Taken</th>
      <th>Score</th>
      <th><i class="fa fa-diamond fa-2x"></i></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @games.each do |game| %>
      <td><%= game.location.city %></td>
      <td><%= game.score %> miles</td>
      <td><%= game.elapsed_time %> seconds</td>
      <td><%= game.points.round %></td>
      <% if game.points >= 5001 %>
        <td><i style="color:#965A38;" class="fa fa-diamond fa-2x"></i></td>
      <% elsif game.points >= 2001 %>
        <td><i style="color:#A8A8A8;" class="fa fa-diamond fa-2x"></i></td>
      <% elsif game.points >= 101 %>
        <td><i style="color:#D9A441;" class="fa fa-diamond fa-2x"></i></td>
      <% else %>
      <td><i style="color:#CCC2C2;" class="fa fa-diamond fa-2x"></i></td>
      <% end %>
    </tr>
      <% end %>
  </tbody>
</table>

<h1 style="text-align:center">Leaderboard</h1>
<table class="ui sortable celled table">
  <thead>
    <tr>
      <th>Level</th>
      <th>Username</th>
      <th>Distance Away</th>
      <th>Time Taken</th>
      <th>Score</th>
      <th><i class="fa fa-diamond fa-2x"></i></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @locations.each do |location| %>
      <td><%= location.city %></td>
      <td><%= link_to location.top_scorer.username, user_path(location.top_scorer) %></td>
      <td><%= location.top_game.score %> miles</td>
      <td><%= location.top_game.elapsed_time %> seconds</td>
      <td><%= location.top_game.points.round %></td>
      <% if location.top_game.points >= 5001 %>
        <td><i style="color:#965A38;" class="fa fa-diamond fa-2x"></i></td>
      <% elsif location.top_game.points >= 2001 %>
        <td><i style="color:#A8A8A8;" class="fa fa-diamond fa-2x"></i></td>
      <% elsif location.top_game.points >= 101 %>
        <td><i style="color:#D9A441;" class="fa fa-diamond fa-2x"></i></td>
      <% else %>
      <td><i style="color:#CCC2C2;" class="fa fa-diamond fa-2x"></i></td>
      <% end %>
    </tr>
      <% end %>
  </tbody>
</table>

<div id="play">
  <div class="ui teal button"><%= link_to "Play Next Level", new_game_path %></div>
</div>

<script>
$(document).ready(function() {

  $("table").tablesort();

});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wayfarer</title>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!--fonts-->
  <link href='https://fonts.googleapis.com/css?family=Raleway:100,400,200,300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Nothing+You+Could+Do' rel='stylesheet' type='text/css'>

  <!--gmaps4rails-->
  <script src="https://maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometrykey=AIzaSyDZPtO2jQcyMxVWc4pgtazVivWuM2qiDiU" type="text/javascript"></script>
  <script src='https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

</head>
<body>
<div class="logged-in">
  <div class="ui text menu right floated">
  <% if user_signed_in? %>
    <i class="item nav">
      <%= link_to "Scores", games_path %>
    </i>
    <i class="item nav">
      <%= link_to "Update Account", edit_user_registration_path %>
    </i>
    <i class="item nav">
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    </i>
    <i class="item nav">
      <%= link_to "Play!", new_game_path %>
    </i>
  </div>
    <div class="ui header"><%= link_to "Wayfarer", root_path %></div>
    <hr>
  <% else %>
    <div class="ui left aligned header"><%= link_to "Wayfarer", root_path %></div>
  <% end %>
</div>


<div class="flash-messages">
  <% if flash[:notice] %>
    <div class="ui teal message"><%= flash[:notice] %></div>
  <% elsif flash[:alert] %>
    <div class="ui pink message"><%= flash[:alert] %></div>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/layouts/external.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wayfarer</title>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!--fonts-->
  <link href='https://fonts.googleapis.com/css?family=Raleway:100,400,200,300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Nothing+You+Could+Do' rel='stylesheet' type='text/css'>

  <!--gmaps4rails-->
  <script src="https://maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometrykey=AIzaSyDZPtO2jQcyMxVWc4pgtazVivWuM2qiDiU" type="text/javascript"></script>
  <script src='https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

</head>
<body>
<%= image_tag "homepage.jpg" %>
  <div class="ui page grid">
    <div class="column">
      <div class="ui text menu">
        <% if user_signed_in? %>
          <i class="item">
            <a href="#about">About</a>
          </i>
          <i class="item">
            <%= link_to "Scores", games_path %>
          </i>
          <i class="item">
            <%= link_to "Update Account", edit_user_registration_path %>
          </i>
          <i class="item">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
          </i>
          <i class="item">
            <%= link_to "Play!", new_game_path %>
          </i>
        <% else %>
          <i class="item">
            <a href="#about">About</a>
          </i>
          <i class="item">
            <%= link_to "Log In", new_user_session_path %>
          </i>
          <i class="item">
            <%= link_to "Sign Up", new_user_registration_path %>
          </i>
          <i class="item">
            <%= link_to "Play!", new_game_path %>
          </i>
        <% end %>
      </div>
      <div class="header"><%= link_to "Wayfarer", root_path %></div>
    </div>
  </div>

  <div class="ui vertical rectangle test ad"></div>

  <div class="ui inverted vertical segment">
    <div class="ui very relaxed stackable page grid">
      <div class="row">
        <div class="column">
          <h1 class="center aligned ui inverted header">
            <a name="about">
              How to Play
            </a>
          </h1>
        </div>
      </div>
      <div class="row">
        <div class="eight wide column">
          <div class="ui inverted animated selection list">
            <div class="item" style="text-align:center">
              GAME PLAY
            </div>
            <div class="item">
              <i class="angle double right icon"></i>Create an account by clicking on "Sign Up" in the menu above.
            </div>
            <div class="item">
              <i class="angle double right icon"></i>Click "Play" to be transported to a Google Street View somewhere in the world...
            </div>
            <div class="item">
              <i class="angle double right icon"></i>You have 30 seconds to walk around in Google Street View to figure out where you are. **HINT be on the lookout for street signs in other languages, names of stores, or famous landmarks!
            </div>
            <div class="item">
              <i class="angle double right icon"></i>If you know where you are, click on the "Guess" button at the bottom of the screen. Otherwise, once the 30 seconds are up, a map will pop up.
            </div>
            <div class="item">
              <i class="angle double right icon"></i>Zoom in on the map and drag the pin to the location you think you have been placed in. Take your time here, the timer has stopped!
            </div>
            <div class="item">
              <i class="angle double right icon"></i>Once you've placed you're pin, click "Submit" to submit your answer.
            </div>
            <div class="item">
              <i class="angle double right icon"></i>You will be redirected to a map with two pins in it. One pin is the location you guessed, and the other is the location you were placed in. See how close you got!
            </div>
            <div class="item">
              <i class="angle double right icon"></i>Click on "Play Next Level" to play again!
            </div>
          </div>
        </div>
        <div class="eight wide column">
          <div class="ui inverted animated selection list">
            <div class="item" style="text-align:center">
              SCORING
            </div>
            <div class="item">
              <i class="angle double right icon"></i>Your score is determined by how many miles away your guess was from your destination and the time it took you to submit your answer. You want to get the LOWEST score, as in the closest to your destination in the shortest amount of time!
            </div>
            <div class="item">
              <i class="angle double right icon"></i>You can click on "Scores" in the menu to see all of your scores.
            </div>
            <div class="item">
              <i class="angle double right icon"></i>Below your scores there is a leaderboard table with the top scores by all users. Only the levels you have played will be displayed.
            </div>
            <div class="item">
              <i class="angle double right icon"></i>You will be given a medal based on your score, platinum, gold, silver, or bronze.
            </div>
            <button class="ui teal animated button huge button">
              <div class="visible content">Let's Play!</div>
              <div class="hidden content"><%= link_to "Let's Play!", new_game_path %></div>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
<div class="ui footer segment">
  <%= image_tag "codecore.jpg" %>
</div>

</body>
</html>

app/views/users/index.html.erb
<div class="guess-button">
  <div class="ui teal button" style="margin: 0 auto"><%= link_to "Go Home", root_path %></div>
</div>

app/views/users/show.html.erb
<div class="users">
  <h2><%= @user.first_name %> <%= @user.last_name%></h2>
</div>

<h1 style="text-align:center"><%= @user.username %>'s Scores</h1>
<table class="ui sortable celled table">
  <thead>
    <tr>
      <th>Level</th>
      <th>Distance Away</th>
      <th>Time Taken</th>
      <th>Score</th>
      <th><i class="fa fa-diamond fa-2x"></i></th>
    </tr>
  </thead>
  <tbody>
    <% @user.locations.each do |location| %>
    <tr>
      <td><%= location.city %></td>
      <td><%= location.games.find_by_user_id(@user.id).score %> miles</td>
      <td><%= location.games.find_by_user_id(@user.id).elapsed_time %> seconds</td>
      <td><%= location.games.find_by_user_id(@user.id).points.round %></td>
      <% if location.games.find_by_user_id(@user.id).points >= 5001 %>
        <td><i style="color:#965A38;" class="fa fa-diamond fa-2x"></i></td>
      <% elsif location.games.find_by_user_id(@user.id).points >= 2001 %>
        <td><i style="color:#A8A8A8;" class="fa fa-diamond fa-2x"></i></td>
      <% elsif location.games.find_by_user_id(@user.id).points >= 101 %>
        <td><i style="color:#D9A441;" class="fa fa-diamond fa-2x"></i></td>
      <% else %>
      <td><i style="color:#CCC2C2;" class="fa fa-diamond fa-2x"></i></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>


<script>
  $(document).ready(function() {

    $("table").tablesort();

  });
</script>